str = "Sun rises in the East"
print(len(str))
print(str.lower())
print(str.casefold())
print(str.upper())
print(str.title())
print(str.capitalize())
print(str)
print(str.strip())
print(str.replace('s','T',2))
print(str.find(" "))
print(str.startswith("Sun"))
print(str.endswith("East"))
print(str.split("e",2))
print("abc".join("xyz"))
print("abc".isalpha())
print("123sdd".isdigit())
print("qbc".isalnum())
print("abc".zfill(8))
print("abc".center(16,"*"))
print(str[2:15:2])
print(str[:8])
print(str[-4:-1])
print(str[-1:-4:-1])
print(str[::-1])